config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :categories
  root 'categories#index'

  get ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'

  devise_for :users

end

app/models/category.rb
class Category < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @header = "HH에 오신 것을 환영합니다."
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @header = @category.title
    @background_image = @category.image_url
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@header = "Welcome To Open Univ data!"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @header = @post.title
    @background_image = @post.image_url
    @subtitle = @post.user.email
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to category_path(@post.category), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :image %>

  <%= f.submit "등록하기", class: "btn btn-info" %>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="marketing">

<!-- Three columns of text below the carousel -->
  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-lg-3 or col-xs-6">
        <%= image_tag category.image_url, class: "img-circle", size: "140x140", alt: "book image" %>
        <h2><%= category.title %></h2>
        <p><%= link_to "View detail", category, class:"btn btn-info" %> </p>
      </div><!-- /.col-lg-4 -->
    <% end %>
  </div><!-- /.row -->
  <hr>
</div>
<%= link_to 'New Category', new_category_path, class:"btn btn-orange" %> | <%= link_to 'New Post', new_post_path, class:"btn btn-orange" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<hr>
<%= link_to 'Back', categories_path, class:"btn btn-info" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @category.posts %>

<hr>
<%= link_to 'Edit', edit_category_path(@category), class:"btn btn-info" %> |
<%= link_to 'Back', categories_path, class:"btn btn-info" %> |
<%= link_to 'New post', new_post_path, class:"btn btn-info" %>

app/views/home/index.html.erb
<div class="container marketing">

<!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-sm-4">
      <%= image_tag "book", class: "img-circle", size: "140x140", alt: "book image" %>
      <h2>BOOK</h2>
      <p></p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-sm-4">
      <%= image_tag "video", class: "img-circle", size: "140x140", alt: "book image" %>
      <h2>VIDEO</h2>
      <p></p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-sm-4">
      <%= image_tag "article", class: "img-circle", size: "140x140", alt: "book image" %>
      <h2>ARTICLE</h2>
      <p></p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->

  <hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://bootswatch.com/journal/bootstrap.min.css">

	<script src="https://bootswatch.com/journal/bootstrap.min.css"></script>
  <title>Hh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%=link_to 'H & H', root_path, class:"navbar-brand page-scroll" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <% Category.all.each do |category| %>
                        <li><%= link_to category.title, category, class: "page-scroll" %></li>
                    <% end %>
                    <% if user_signed_in? %>
                        <li>
                            <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class:"page-scroll" %>
                        </li>
                    <% else %>
                        <li>
                            <%= link_to "로그인",new_user_session_path, class:"page-scroll" %>
                        </li>
                        <li>
                            <%= link_to "회원가입",new_user_registration_path, class:"page-scroll"%>
                        </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header class="intro-header" style="background-image: url('<%= @background_image or asset_path('header-bg.jpg') %>')">
        <div class="container">
            <div class="intro-text">
                <div class="intro-heading"><%= @header %></div>
                <div class="intro-lead-in"><%= @subtitle %></div>
                <!-- <a href="#services" class="page-scroll btn btn-xl">More</a> -->
            </div>
        </div>
    </header>    

    <div class="container">
        <%= yield %>
    </div>
	<footer>
        <STRONG><p class="center">@made by HEE&HYEOK</p></STRONG>
    </footer>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :image %>
    <%= f.association :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-info" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
  <div class="media-left">
  	<%= link_to image_tag(post.image_url(:thumb), class: "media-object", size: "64x64"), post %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= link_to post.title, post %></h4>
    <%= truncate(post.content, length: 200) %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.image %></td>
        <td><%= post.category %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<hr>
<%= link_to 'Back', categories_path, class:"btn btn-info" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= simple_format(@post.content) %>
</p>

<p>
  카테고리: <%= link_to @post.category.title, @post.category %>
</p>

<hr>
<%= link_to 'Edit', edit_post_path(@post), class:"btn btn-info" %> |
<%= link_to 'Back', category_path(@post.category), class:"btn btn-info" %> |
<%= link_to 'Destroy', post_path(@post), method: :delete, class:"btn btn-info" %>